### ISSUE TITLE
About the source of the relationship table between delta e and perception

### ISSUE THREAD

**Issue by Bubbleinpit** [zschuessler/DeltaE#10]
Hello, I want to know where the [table](http://zschuessler.github.io/DeltaE/learn/#toc-defining-delta-e) of the relationship between delta e and perception given in your document comes from? Is there any literature supporting the data in the table?

**Comment by zschuessler** [comment]
Hi there,

I just updated the guide to reflect the answer: I built the table from my own tests. An authority source hasn't built a similar table, the best I found during research was a document that a printing company developed that listed their own threshold values, but not quite in the same way.

Perception is quite subjective, and changes depending on which dE algo you're using :-)

Thanks for reaching out!
