### ISSUE TITLE
Calculation wrong

### ISSUE THREAD

**Issue by ddsol** [zschuessler/DeltaE#4]
This Delta E calculation is wrong. For some insight I suggest reading [this paper](http://www.ece.rochester.edu/~gsharma/ciede2000/ciede2000noteCRNA.pdf).

Details:
```js
de({l: 60, a: -79.86355100472929, b: 60.18150231520482}, {l: 60, a: 79.86355100472929, b: -60.181502315204824}) = 59.58968443596155;

de({l: 60, a: -79.86355100472929, b: 60.18150231520482}, {l: 60, a: 79.863656041144, b: -60.18136292692152}) = 102.06502930178404;
```

How can that be right when the difference in the second color is extremely small (and no difference in the first color) but the resulting Delta E is radically different?

**Comment by zschuessler** [comment]
I've verified the calculation is correct here:
http://colormine.org/delta-e-calculator/cie2000

I read the linked resource when creating this library. Does something specific exist in the paper which refutes the accuracy of the implementation?

(By the way, de00 gives inaccurate results when there is a hue shift of 180/360 degrees. this is mentioned in the paper)

**Comment by zschuessler** [comment]
I just noticed in your original message you said the difference in color is extremely small. Are you using the CIELAB color space? The colors are drastically different. Bright green vs bright pink.

You can also tell the colors are polar  opposites in hue because the colors are inverted in A/B values.

**Comment by ddsol** [comment]
Well, I fed all the test data in that paper through this function and it looks like the results are the same.
The difference in the second color is extremely small in both cases. But it is a flip at the 180° mark.

Also, the paper only tests colors with a very small color difference (R<2.5) so the discontinuity is small there. But as you can see above, the discontinuity is huge.

That said, DeltaE is apparently just really bad at diffing colors where dE>5 or so. So, `if (dE00(a,b)>5) return NaN;` 😄.

From the paper:

> Though the CIEDE2000 color-difference equations **_are only applicable for small color differences_**, it is preferable that data for testing software implementations should include at least a few large color differences

**Comment by zschuessler** [comment]
Momma always said nothing was perfect :wink: 

Reviewing this, it _would_ be cool if discontinuity was calculated. Too specific of a use case and time consuming for it to be a good addition I think.

Cheers!
